use crate::{
    archive::Archive,
    download,
    models::{
        manifest::{legacy, Manifest, Source},
        Mod,
    },
    sources,
    utils::{copy_dir_recursive, detect_patch_layout, PatchLayout},
    AppState,
};
use anyhow_tauri::{IntoTAResult, TAResult};
use rand::{rngs::SysRng, TryRng};
use serde::Serialize;
use std::{collections::HashSet, path::{Path, PathBuf}};
use tauri::State;
use uuid::Uuid;

pub(crate) const MODS_DIRECTORY: &'static str = "mods/";
const MANIFEST_FILE: &'static str = "manifest.json";
const NO_PATCH_FILES_WARNING: &str = "no Helldivers 2 patch files found in this archive";

/// The JSON shape returned by every install command: a [`Mod`] plus an
/// optional, non-fatal warning (currently only "no Helldivers 2 patch files
/// found").
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "PascalCase")]
pub struct InstalledMod {
    #[serde(flatten)]
    pub r#mod: Mod,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
}

/// A manifest counts as "generated by us" (as opposed to one an author
/// shipped) exactly when it's the `LOCAL`-prefixed legacy manifest
/// `generate_local_manifest` produces. Only those are safe to rewrite with
/// an auto-detected `Options` list -- an author's own manifest.json is
/// never touched.
fn is_local_generated(manifest: &Manifest) -> bool {
    matches!(manifest, Manifest::Legacy(m) if m.guid.as_bytes().get(..5) == Some(b"LOCAL"))
}

/// After extraction/copy, if (and only if) the manifest was generated by us
/// because the mod shipped no `manifest.json` of its own, look for where
/// the actual Helldivers 2 patch files ended up and, if they're not at the
/// mod root, fill in `Options` (persisting the rewritten manifest.json) so
/// deploy and the existing option picker find them without any further
/// user action. Returns a non-fatal warning if no patch files were found
/// anywhere.
async fn apply_patch_layout(mod_dir: &Path, manifest: &mut Manifest) -> anyhow::Result<Option<String>> {
    if !is_local_generated(manifest) {
        return Ok(None);
    }

    let layout = detect_patch_layout(mod_dir).await?;

    match layout {
        PatchLayout::RootHasFiles => Ok(None),
        PatchLayout::Options(paths) => {
            if let Manifest::Legacy(legacy) = manifest {
                legacy.options = Some(paths);
            }
            let manifest_file = mod_dir.join(MANIFEST_FILE);
            let data = serde_json::to_vec_pretty(manifest)?;
            tokio::fs::write(manifest_file, data).await?;
            Ok(None)
        }
        PatchLayout::NoneFound => Ok(Some(NO_PATCH_FILES_WARNING.to_string())),
    }
}

#[allow(dead_code)]
trait ZipResult<S, E, T> {
    fn zip(self, other: Result<T, E>) -> Result<(S, T), E>;
    fn zip_value(self, other: T) -> Result<(S, T), E>;
}

impl<S, E, T> ZipResult<S, E, T> for Result<S, E> {
    fn zip(self, other: Result<T, E>) -> Result<(S, T), E> {
        match (self, other) {
            (Ok(a), Ok(b)) => Ok((a, b)),
            (Err(e), Ok(_)) => Err(e),
            (Ok(_), Err(e)) => Err(e),
            (Err(e), Err(_)) => Err(e),
        }
    }

    fn zip_value(self, other: T) -> Result<(S, T), E> {
        match self {
            Ok(s) => Ok((s, other)),
            Err(e) => Err(e)
        }
    }
}

/// Resolve an image path from a mod's manifest (`IconPath`, an option's
/// `Image`) to the file on disk, with the same rules as deploy
/// ([`crate::utils::fix_path_casing`]: `\` separators, any casing, never
/// outside the mod folder). `None` when there's no such file, so the UI
/// shows its default icon. Only answers for folders inside `mods/`.
pub(crate) async fn resolve_mod_image_path(base_path: &Path, mod_directory: &Path, image: &str) -> Option<PathBuf> {
    let mods_root = tokio::fs::canonicalize(base_path.join(MODS_DIRECTORY)).await.ok()?;
    let mod_dir = tokio::fs::canonicalize(mod_directory).await.ok()?;
    if !mod_dir.starts_with(&mods_root) || mod_dir == mods_root {
        return None;
    }
    let relative = crate::utils::fix_path_casing(&mod_dir, Path::new(image)).await.ok()?;
    if relative.as_os_str().is_empty() {
        return None;
    }
    // Hand back the path as the app knows it (not the canonical form, which
    // is `\\?\C:\…` on Windows); the asset scope allows both.
    let file = mod_directory.join(relative);
    tokio::fs::metadata(&file).await.ok().filter(|m| m.is_file()).map(|_| file)
}

#[tauri::command]
pub async fn resolve_mod_image(
    state: State<'_, AppState>,
    mod_directory: PathBuf,
    image: String,
) -> TAResult<Option<PathBuf>> {
    Ok(resolve_mod_image_path(&state.base_path, &mod_directory, &image).await)
}

#[tauri::command]
pub async fn get_mods(state: State<'_, AppState>) -> TAResult<Vec<Mod>> {
    let mut state_mods = state.mods.lock().await;
    log::info!("Loading mods...");
    let mods = ensure_mods_loaded(&mut state_mods, &state.base_path).await?;
    Ok(mods.clone())
}

/// Read every installed mod from disk into `state_mods` the first time it's
/// needed (a no-op once loaded) and return it. Shared by `get_mods` and by
/// the browser bridge, which can receive an install before the frontend
/// has ever called `get_mods` -- e.g. a first run still on the Settings
/// page, or DDMM just launched by the native-messaging host.
pub(crate) async fn ensure_mods_loaded<'a>(
    state_mods: &'a mut Option<Vec<Mod>>,
    base_path: &Path,
) -> TAResult<&'a mut Vec<Mod>> {
    if state_mods.is_some() {
        log::debug!("Mods already loaded.");
        return Ok(state_mods.as_mut().unwrap());
    }

    let mods_dir = base_path.join(MODS_DIRECTORY);
    let mut mods = Vec::new();
    if !mods_dir.is_dir() {
        // First run: nothing installed yet. Still record the (empty) list
        // as loaded, or every install command would fail with "mods not
        // read" until something called get_mods a second time.
        tokio::fs::create_dir_all(&mods_dir).await.into_ta_result()?;
    } else {
        let mut mods_dir = tokio::fs::read_dir(mods_dir).await.into_ta_result()?;
        while let Some(entry) = mods_dir.next_entry().await.into_ta_result()? {
            let mod_dir = entry.path();

            let manifest_file = mod_dir.join(MANIFEST_FILE);
            if !manifest_file.is_file() {
                continue;
            }

            // One unreadable manifest must not take the whole library down
            // with it (every later install would then fail with "mods not
            // read"): log it with the reason and skip that mod.
            let manifest = match tokio::fs::read(&manifest_file).await {
                Ok(data) => Manifest::parse(&data, &manifest_file.to_string_lossy()),
                Err(e) => Err(anyhow::anyhow!("can't read {:?}: {}", manifest_file, e)),
            };
            let manifest = match manifest {
                Ok(m) => m,
                Err(e) => {
                    log::error!("Skipping mod in {:?}: {:#}", mod_dir, e);
                    continue;
                }
            };

            let mut r#mod = Mod {
                manifest,
                directory: mod_dir,
                sources: Vec::new(),
            };
            if let Err(e) = r#mod.normalize_paths().await {
                log::error!("Path normalization failed for {:?}: {:#}", r#mod.directory, e);
            }
            r#mod.resolve_sources().await;

            mods.push(r#mod);
        }
    }

    log::info!("Mods loaded.");
    Ok(state_mods.insert(mods))
}

#[tauri::command]
pub async fn delete_mod(state: State<'_, AppState>, guid: Uuid) -> TAResult<()> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    log::info!("Deleting mod \"{}\"...", guid);

    if let Some(i) = mods.iter().position(|m| m.guid() == guid) {
        let r#mod = mods.remove(i);
        log::info!("Mod removed form registry.");

        log::info!("Deleting files...");
        tokio::fs::remove_dir_all(r#mod.directory).await.into_ta_result()?;
        
        log::info!("Mod deletion complete.");
        Ok(())
    } else {
        anyhow_tauri::bail!("mod with GUID {{{}}} not found", guid);
    }
}

#[tauri::command]
pub async fn add_mod(state: State<'_, AppState>, archive_file: PathBuf) -> TAResult<InstalledMod> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    let (r#mod, warning) = install_from_archive(&state, mods, &archive_file).await?;
    Ok(InstalledMod { r#mod, warning })
}

/// Shared core of `add_mod`: prepares the mod directory, resolves the
/// manifest (from the archive if present, generating a local one
/// otherwise), extracts, and registers the mod.
///
/// Takes the already-locked mods vector rather than `State` directly so it
/// can be called both from a `#[tauri::command]` that holds the lock for a
/// single install, and from callers (like `add_paths`) that lock once per
/// item without ever calling back into another `#[tauri::command]` while
/// holding the mutex.
pub(crate) async fn install_from_archive(state: &AppState, mods: &mut Vec<Mod>, archive_file: &Path) -> TAResult<(Mod, Option<String>)> {
    log::info!("Adding mod from {:?}...", archive_file);

    log::debug!("Opening archive...");
    let archive = Archive::open(archive_file)?;

    log::debug!("Obtaining name...");
    let name = archive_file
        .file_prefix()
        .unwrap()
        .to_str()
        .map(str::to_string)
        .ok_or(anyhow::anyhow!("file name conversion failed"))?;

    log::info!("Resolving mod directory...");
    let mut mod_dir = state.base_path.join(MODS_DIRECTORY);
    mod_dir.push(&name);

    log::info!("Preparing mod directory...");
    let manifest_file = mod_dir.join(MANIFEST_FILE);
    prepare_mod_dir(archive_file, mod_dir.clone(), manifest_file.clone(), name.clone()).await.into_ta_result()?;

    // From here on `mod_dir` is ours (prepare_mod_dir just created it), so
    // a failure must remove it again: a half-written directory with a
    // manifest.json would otherwise show up as an empty "ghost" mod on the
    // next launch and block retrying the same file with "mod directory
    // already exists" (e.g. after an archive was rejected as unsafe).
    let prepared: TAResult<(Mod, Option<String>)> = async {
        log::info!("Resolving manifest...");
        let (archive, manifest) = resolve_manifest(archive, name.clone(), manifest_file.clone()).await.into_ta_result()?;

        let mut r#mod = Mod {
            manifest,
            directory: mod_dir.clone(),
            sources: Vec::new(),
        };

        log::info!("Checking for duplicate...");
        if mods.iter().any(|m| m.guid() == r#mod.guid()) {
            return anyhow::anyhow!("mod with GUID {{{}}} already exists", r#mod.guid())
                .into_ta_result();
        }

        log::info!("Extracting archive...");
        extract_archive(archive, mod_dir.clone()).await?;

        log::debug!("Detecting patch file layout...");
        let warning = apply_patch_layout(&mod_dir, &mut r#mod.manifest).await.into_ta_result()?;
        Ok((r#mod, warning))
    }
    .await;
    let (mut r#mod, warning) = match prepared {
        Ok(v) => v,
        Err(e) => {
            if let Err(cleanup) = tokio::fs::remove_dir_all(&mod_dir).await {
                log::error!("Failed to clean up {:?} after a failed install: {}", mod_dir, cleanup);
            }
            return Err(e);
        }
    };

    log::debug!("Normalizing paths...");
    if let Err(e) = r#mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }

    r#mod.resolve_sources().await;

    mods.push(r#mod.clone());
    log::info!("Mod successfully added.");
    Ok((r#mod, warning))
}

#[tauri::command]
pub async fn add_mods(state: State<'_, AppState>, archive_files: Vec<PathBuf>) -> TAResult<Vec<TAResult<InstalledMod>>> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    log::info!("Adding mods from:",);
    for archive_file in &archive_files {
        log::info!(" - {:?}", archive_file);
    }
    
    log::debug!("Opening archives...");
    let data = archive_files
        .iter()
        .map(|archive_file| Archive::open(archive_file).into_ta_result())
        .collect::<Vec<_>>();

    log::debug!("Obtaining names...");
    let data = archive_files
        .iter()
        .cloned()
        .zip(data)
        .map(|(archive_file, result)| {
            result
                .zip_value(archive_file)
                .map(|(archive, archive_file)| {
                    let name = archive_file
                        .file_prefix()
                        .unwrap()
                        .to_str()
                        .map(str::to_string)
                        .ok_or(anyhow::anyhow!("file name conversion failed"))
                        .into_ta_result()?;
                    Ok((archive, name, archive_file))
                })
                .flatten()
        })
        .collect::<Vec<_>>();

    log::info!("Resolving mod directories...");
    let data = data
        .into_iter()
        .map(|result| {
            result
                .map(|(archive, name, archive_file)| {
                    let mut mod_dir = state.base_path.join(MODS_DIRECTORY);
                    mod_dir.push(&name);
                    let manifest_file = mod_dir.join(MANIFEST_FILE);
                    (archive, name, archive_file, mod_dir, manifest_file)
                })
        })
        .collect::<Vec<_>>();

    log::info!("Preparing mod directories...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, name, archive_file, mod_dir, manifest_file)) => {
                    prepare_mod_dir(&archive_file, mod_dir.clone(), manifest_file.clone(), name.clone()).await?;
                    Ok((archive, name, mod_dir, manifest_file))
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    log::info!("Resolving manifests...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, name, mod_dir, manifest_file)) => {
                    let (archive, manifest) = resolve_manifest(archive, name, manifest_file).await?;
                    Ok((archive, mod_dir, manifest))
                }
                Err(e) => Err(e)
            }
        })
    ).await;
    
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, mod_dir, manifest)| {
                let r#mod = Mod {
                    manifest,
                    directory: mod_dir,
                    sources: Vec::new(),
                };
                (archive, r#mod)
            })
        })
        .collect::<Vec<_>>();
    
    log::info!("Checking for duplicates...");
    let mut guids: HashSet<Uuid> = mods.iter().map(|m| m.guid()).collect();
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, r#mod)| {
                let guid = r#mod.guid();
                if guids.insert(guid) {
                    Ok((archive, r#mod))
                } else {
                    anyhow_tauri::bail!("mod with GUID {{{}}} already exists", guid)
                }
            })
            .flatten()
        })
        .collect::<Vec<_>>();

    let mut guids = HashSet::<Uuid>::new();
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, r#mod)| {
                let guid = r#mod.guid();
                if guids.insert(guid) {
                    Ok((archive, r#mod))
                } else {
                    anyhow_tauri::bail!("already adding mod with GUID {{{}}}", guid)
                }
            })
            .flatten()
        })
        .collect::<Vec<_>>();

    log::info!("Extracting archives...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, r#mod)) => {
                    extract_archive(archive, r#mod.directory.clone()).await?;
                    Ok(r#mod)
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    log::debug!("Detecting patch file layouts and normalizing paths...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok(mut r#mod) => {
                    let warning = match apply_patch_layout(&r#mod.directory.clone(), &mut r#mod.manifest).await {
                        Ok(w) => w,
                        Err(e) => {
                            log::error!("Patch layout detection failed for \"{}\": {}", r#mod.guid(), e);
                            None
                        }
                    };
                    if let Err(e) = r#mod.normalize_paths().await {
                        log::error!("Path normalization failed for \"{}\": {}", r#mod.guid(), e);
                    }
                    r#mod.resolve_sources().await;
                    Ok((r#mod, warning))
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    for (r#mod, _) in data.iter().flatten() {
        mods.push(r#mod.clone());
    }

    log::info!("Adding complete.");
    for (p, r) in archive_files.iter().zip(&data) {
        if let Err(e) = r {
            log::info!(" - {:?} : Err -> {}", p, e);
        } else {
            log::info!(" - {:?} : Ok", p);
        }
    }

    let data = data
        .into_iter()
        .map(|result| result.map(|(r#mod, warning)| InstalledMod { r#mod, warning }))
        .collect::<Vec<_>>();

    Ok(data)
}

/// Make `mod_dir` ready to install into from `source` (an archive file or a
/// folder): an existing mod there is an error, a leftover folder without a
/// manifest is cleared, and the folder is (re)created.
///
/// Refuses first if `source` and `mod_dir` overlap -- clearing or copying
/// into `mod_dir` would then delete the source or copy it into itself.
async fn prepare_mod_dir(source: &Path, mod_dir: PathBuf, manifest_file: PathBuf, name: String) -> TAResult<()> {
    if crate::fs_util::path_overlap(source, &mod_dir).into_ta_result()?.is_some() {
        return anyhow::anyhow!(
            "can't install {:?}: it is inside (or is) the folder DDMM would install it into ({:?}). \
             Move it somewhere outside DDMM's mod storage and add it from there.",
            source,
            mod_dir
        )
        .into_ta_result();
    }
    if tokio::fs::try_exists(&mod_dir).await.into_ta_result()? {
        if tokio::fs::try_exists(&manifest_file).await.into_ta_result()? {
            return anyhow::anyhow!("mod directory \"{}\" already exists", name).into_ta_result();
        } else {
            tokio::fs::remove_dir_all(&mod_dir).await.into_ta_result()?;
        }
    }
    tokio::fs::create_dir_all(&mod_dir).await.into_ta_result()
}

/// Generate the same "no manifest present" local legacy manifest, whether
/// the mod came from an archive with no `manifest.json`, or a plain folder
/// with no `manifest.json`.
fn generate_local_manifest(name: String) -> anyhow::Result<Manifest> {
    let mut guid = [0u8; 16];
    guid[..5].copy_from_slice(b"LOCAL");
    SysRng.try_fill_bytes(&mut guid[5..])?;

    Ok(Manifest::Legacy(legacy::Manifest {
        guid: Uuid::from_bytes(guid),
        name,
        description: String::new(),
        icon_path: None,
        options: None,
    }))
}

async fn resolve_manifest(mut archive: Archive, name: String, manifest_file: PathBuf) -> TAResult<(Archive, Manifest)> {
    if let Some(entry) = archive.find_root_file_ci(MANIFEST_FILE)? {
        let manifest_data = archive.read_path(&entry)?;
        let origin = format!("{} in archive \"{}\"", entry.display(), name);
        let manifest = Manifest::parse(&manifest_data, &origin).into_ta_result()?;
        Ok((archive, manifest))
    } else {
        let manifest = generate_local_manifest(name).into_ta_result()?;

        let manifest_data = serde_json::to_vec_pretty(&manifest).into_ta_result()?;
        tokio::fs::write(&manifest_file, manifest_data)
            .await
            .into_ta_result()?;

        Ok((archive, manifest))
    }
}

/// Same idea as [`resolve_manifest`], but for a plain folder install: read
/// `manifest.json` from the source folder if present, otherwise generate a
/// local one and write it straight into the (already-created) destination
/// mod directory.
async fn resolve_manifest_for_dir(source_dir: &Path, name: String, manifest_file: PathBuf) -> TAResult<Manifest> {
    let source_manifest = find_manifest_file(source_dir).await;
    if let Some(source_manifest) = source_manifest {
        let manifest_data = tokio::fs::read(&source_manifest).await.into_ta_result()?;
        let manifest = Manifest::parse(&manifest_data, &source_manifest.to_string_lossy()).into_ta_result()?;
        Ok(manifest)
    } else {
        let manifest = generate_local_manifest(name).into_ta_result()?;

        let manifest_data = serde_json::to_vec_pretty(&manifest).into_ta_result()?;
        tokio::fs::write(&manifest_file, manifest_data)
            .await
            .into_ta_result()?;

        Ok(manifest)
    }
}

async fn extract_archive(mut archive: Archive, mod_dir: PathBuf) -> TAResult<()> {
    let dir = mod_dir.clone();
    tokio::task::spawn_blocking(move || archive.extract_to(dir).into_ta_result()).await.into_ta_result()??;
    normalize_manifest_file_name(&mod_dir).await.into_ta_result()
}

/// `dir`'s manifest file: `manifest.json`, or failing that a case variant
/// such as `Manifest.json` (fine on Windows, invisible to an exact lookup
/// on Linux's case-sensitive filesystems).
async fn find_manifest_file(dir: &Path) -> Option<PathBuf> {
    let exact = dir.join(MANIFEST_FILE);
    if exact.is_file() {
        return Some(exact);
    }
    let mut entries = tokio::fs::read_dir(dir).await.ok()?;
    while let Ok(Some(entry)) = entries.next_entry().await {
        if entry.file_name().to_string_lossy().eq_ignore_ascii_case(MANIFEST_FILE)
            && entry.file_type().await.map(|t| t.is_file()).unwrap_or(false)
        {
            return Some(entry.path());
        }
    }
    None
}

/// After extracting/copying a mod, rename a `Manifest.json`-style case
/// variant to exactly `manifest.json`, which is what loading the library
/// looks for -- otherwise, on Linux, the mod would disappear on restart.
async fn normalize_manifest_file_name(mod_dir: &Path) -> anyhow::Result<()> {
    let exact = mod_dir.join(MANIFEST_FILE);
    if exact.is_file() {
        return Ok(());
    }
    if let Some(variant) = find_manifest_file(mod_dir).await {
        log::info!("Renaming {:?} to {:?}", variant, exact);
        crate::fs_util::move_path(&variant, &exact).await?;
    }
    Ok(())
}

/// Install a mod from a plain, already-unpacked folder: `folder` becomes the
/// mod's source, its `manifest.json` is used if present (otherwise a local
/// one is generated), and its contents are copied (not moved, symlinks not
/// followed) into the managed mod directory.
///
/// `folder` must not overlap DDMM's own mod storage (`<data>/mods`), which
/// is checked before anything on disk is touched:
/// - the storage folder itself, a folder containing it (such as DDMM's data
///   folder in a portable install), or a folder deeper inside an installed
///   mod is refused with an explanation -- copying any of those would copy
///   the folder into itself, over and over, until the disk is full;
/// - a mod folder sitting directly in the storage folder is adopted in
///   place ([`adopt_folder_in_place`]): nothing is copied, it just gets a
///   manifest and joins the mod list.
///
/// Mirrors [`install_from_archive`]'s locking contract: takes the
/// already-locked mods vector, never locks anything itself.
async fn install_from_folder(base_path: &Path, mods: &mut Vec<Mod>, folder: &Path) -> TAResult<(Mod, Option<String>)> {
    log::info!("Adding mod from folder {:?}...", folder);

    if !folder.is_dir() {
        return anyhow::anyhow!("path is not a directory").into_ta_result();
    }

    let mods_root = base_path.join(MODS_DIRECTORY);
    let resolved = crate::fs_util::resolve_path(folder).into_ta_result()?;

    let name = resolved
        .file_name()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .ok_or(anyhow::anyhow!("folder name conversion failed"))?;

    use crate::fs_util::{path_overlap, PathOverlap};
    match path_overlap(&resolved, &mods_root).into_ta_result()? {
        None => {}
        Some(PathOverlap::Same) => {
            return anyhow::anyhow!(
                "That folder is DDMM's own mod storage ({}), so there is nothing to copy. \
                 Mods in it that have a manifest.json are already in your mod list. To add a \
                 mod folder that is in there without one, pick that mod's own folder instead: \
                 DDMM will set it up where it is, without copying it.",
                mods_root.display()
            )
            .into_ta_result();
        }
        Some(PathOverlap::SecondInsideFirst) => {
            return anyhow::anyhow!(
                "DDMM can't add {}: DDMM's own mod storage ({}) is inside it, so adding it would \
                 copy the folder into itself. Pick a single mod's folder instead.",
                folder.display(),
                mods_root.display()
            )
            .into_ta_result();
        }
        Some(PathOverlap::FirstInsideSecond) => {
            let directly_in_storage = resolved
                .parent()
                .map(|parent| matches!(path_overlap(parent, &mods_root), Ok(Some(PathOverlap::Same))))
                .unwrap_or(false);
            if directly_in_storage {
                return adopt_folder_in_place(mods, &mods_root.join(&name), &name).await;
            }
            return anyhow::anyhow!(
                "{} is inside a mod folder in DDMM's mod storage ({}). Pick that mod's own \
                 folder (the one directly inside the storage folder), or a folder outside it.",
                folder.display(),
                mods_root.display()
            )
            .into_ta_result();
        }
    }

    log::info!("Resolving mod directory...");
    let mod_dir = mods_root.join(&name);

    log::info!("Preparing mod directory...");
    let manifest_file = mod_dir.join(MANIFEST_FILE);
    prepare_mod_dir(folder, mod_dir.clone(), manifest_file.clone(), name.clone()).await.into_ta_result()?;

    // From here on `mod_dir` is a folder we just created (and, per the
    // checks above, not the source or anywhere near it), so a failure must
    // remove it again rather than leave a half-copied mod behind.
    let result = install_from_folder_inner(mods, folder, &name, &mod_dir, &manifest_file).await;

    if result.is_err() {
        if let Err(cleanup) = tokio::fs::remove_dir_all(&mod_dir).await {
            log::error!("Failed to clean up {:?} after a failed install: {}", mod_dir, cleanup);
        }
    }

    result
}

/// Register a folder that already sits directly in DDMM's mod storage as a
/// mod, without copying it: its own `manifest.json` is used if it has one,
/// otherwise a local one is generated and written into it (and removed
/// again if registering fails). Nothing else in the folder is touched, and
/// the folder is never deleted.
async fn adopt_folder_in_place(mods: &mut Vec<Mod>, mod_dir: &Path, name: &str) -> TAResult<(Mod, Option<String>)> {
    use crate::fs_util::{path_overlap, PathOverlap};

    log::info!("{:?} is already in the mod storage; adopting it in place.", mod_dir);

    if let Some(existing) = mods
        .iter()
        .find(|m| matches!(path_overlap(&m.directory, mod_dir), Ok(Some(PathOverlap::Same))))
    {
        return anyhow::anyhow!("\"{}\" is already installed (it's in your mod list)", existing.name())
            .into_ta_result();
    }

    let manifest_file = mod_dir.join(MANIFEST_FILE);
    let had_manifest = find_manifest_file(mod_dir).await.is_some();

    let result: TAResult<(Mod, Option<String>)> = async {
        let manifest = resolve_manifest_for_dir(mod_dir, name.to_string(), manifest_file.clone()).await?;
        let mut r#mod = Mod {
            manifest,
            directory: mod_dir.to_path_buf(),
            sources: Vec::new(),
        };

        if mods.iter().any(|m| m.guid() == r#mod.guid()) {
            return anyhow::anyhow!("mod with GUID {{{}}} already exists", r#mod.guid()).into_ta_result();
        }

        normalize_manifest_file_name(mod_dir).await.into_ta_result()?;
        let warning = apply_patch_layout(mod_dir, &mut r#mod.manifest).await.into_ta_result()?;
        Ok((r#mod, warning))
    }
    .await;

    let (mut r#mod, warning) = match result {
        Ok(v) => v,
        Err(e) => {
            if !had_manifest {
                let _ = tokio::fs::remove_file(&manifest_file).await;
            }
            return Err(e);
        }
    };

    if let Err(e) = r#mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }
    r#mod.resolve_sources().await;

    mods.push(r#mod.clone());
    log::info!("Mod adopted in place.");
    Ok((r#mod, warning))
}

async fn install_from_folder_inner(
    mods: &mut Vec<Mod>,
    folder: &Path,
    name: &str,
    mod_dir: &Path,
    manifest_file: &Path,
) -> TAResult<(Mod, Option<String>)> {
    log::info!("Resolving manifest...");
    let manifest = resolve_manifest_for_dir(folder, name.to_string(), manifest_file.to_path_buf()).await?;

    let mut r#mod = Mod {
        manifest,
        directory: mod_dir.to_path_buf(),
        sources: Vec::new(),
    };

    log::info!("Checking for duplicate...");
    if mods.iter().any(|m| m.guid() == r#mod.guid()) {
        return anyhow::anyhow!("mod with GUID {{{}}} already exists", r#mod.guid())
            .into_ta_result();
    }

    log::info!("Copying folder contents...");
    copy_dir_recursive(folder, mod_dir, &[sources::ORIGIN_SIDECAR_FILE])
        .await
        .into_ta_result()?;
    normalize_manifest_file_name(mod_dir).await.into_ta_result()?;

    log::debug!("Detecting patch file layout...");
    let warning = apply_patch_layout(mod_dir, &mut r#mod.manifest).await.into_ta_result()?;

    log::debug!("Normalizing paths...");
    if let Err(e) = r#mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }

    r#mod.resolve_sources().await;

    mods.push(r#mod.clone());
    log::info!("Mod successfully added.");
    Ok((r#mod, warning))
}

#[tauri::command]
pub async fn add_mod_folder(state: State<'_, AppState>, folder: PathBuf) -> TAResult<InstalledMod> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    let (r#mod, warning) = install_from_folder(&state.base_path, mods, &folder).await?;
    Ok(InstalledMod { r#mod, warning })
}

/// Install any mix of archive files and plain folders in one go, dispatching
/// each path to the right installer. Each path locks the mods mutex
/// independently, so one item's failure never blocks the rest and nothing
/// ever nests a lock inside another lock.
#[tauri::command]
pub async fn add_paths(state: State<'_, AppState>, paths: Vec<PathBuf>) -> TAResult<Vec<TAResult<InstalledMod>>> {
    log::info!("Adding mods from {} path(s)...", paths.len());

    let mut results = Vec::with_capacity(paths.len());
    for path in paths {
        let is_dir = tokio::fs::metadata(&path)
            .await
            .map(|m| m.is_dir())
            .unwrap_or(false);

        let result = if is_dir {
            let mut mods = state.mods.lock().await;
            match mods.as_mut() {
                Some(mods) => install_from_folder(&state.base_path, mods, &path).await,
                None => anyhow::anyhow!("mods not read").into_ta_result(),
            }
        } else {
            let mut mods = state.mods.lock().await;
            match mods.as_mut() {
                Some(mods) => install_from_archive(&state, mods, &path).await,
                None => anyhow::anyhow!("mods not read").into_ta_result(),
            }
        };

        if let Err(e) = &result {
            log::error!("Adding {:?} failed: {}", path, e);
        }
        results.push(result.map(|(r#mod, warning)| InstalledMod { r#mod, warning }));
    }

    Ok(results)
}

/// Install a mod by downloading an archive from a direct `https://` URL
/// first (into a throwaway temp directory), then running it through the
/// same install path as a locally picked archive file. Records where the
/// mod came from in a `.hd2mm-origin.json` sidecar next to the mod, without
/// ever touching the author's own `manifest.json`.
#[tauri::command]
pub async fn add_mod_from_url(state: State<'_, AppState>, url: String) -> TAResult<InstalledMod> {
    log::info!("Downloading mod from {}...", download::redact_url(&url));

    let staging_root = state.base_path.join(download::STAGING_DIRECTORY);
    let downloaded = download::download_archive(&url, &staging_root).await.into_ta_result()?;

    let install_result = {
        let mut mods = state.mods.lock().await;
        match mods.as_mut() {
            Some(mods) => install_from_archive(&state, mods, &downloaded.path).await,
            None => anyhow::anyhow!("mods not read").into_ta_result(),
        }
    };

    // The staged download (and its throwaway parent directory) is no longer
    // needed either way -- the archive contents were copied out on success.
    let _ = tokio::fs::remove_dir_all(&downloaded.temp_dir).await;

    let (mut r#mod, warning) = install_result?;

    log::info!("Recording install origin...");
    let mut origin_source = sources::source_from_page_url(&url).unwrap_or_else(|| Source {
        provider: sources::provider_from_url(&url),
        id: None,
        url: Some(url.clone()),
        version: None,
    });
    // A GitHub release-asset link names its release: record that as the
    // installed version, so update checks work for this mod right away.
    let mut installed_files = Vec::new();
    if let Some(tag) = sources::github_tag_from_download_url(&url) {
        origin_source.version = Some(tag);
        installed_files.push(sources::InstalledFile {
            provider: "github".to_string(),
            file_name: url.rsplit('/').next().map(|n| {
                percent_encoding::percent_decode_str(n.split(['?', '#']).next().unwrap_or(n))
                    .decode_utf8_lossy()
                    .into_owned()
            }),
            ..Default::default()
        });
    }
    if let Err(e) =
        sources::write_origin_sidecar_with_files(&r#mod.directory, vec![origin_source], installed_files).await
    {
        log::error!("Failed to write origin sidecar: {}", e);
    }

    r#mod.resolve_sources().await;

    {
        let mut mods = state.mods.lock().await;
        if let Some(mods) = mods.as_mut() {
            if let Some(existing) = mods.iter_mut().find(|m| m.guid() == r#mod.guid()) {
                *existing = r#mod.clone();
            }
        }
    }

    Ok(InstalledMod { r#mod, warning })
}
/// Install `archive_path` as an update of the existing mod `existing_guid`,
/// used by both the browser handoff and the "Update from {site}" flow.
///
/// The new content is fully staged (extracted, manifest resolved, patch
/// layout detected) in a throwaway directory under the mods folder before
/// anything about the existing mod is touched. Only once that succeeds is
/// the old mod directory swapped out for the new one; on any failure before
/// the swap the old mod is left completely untouched, and the staging
/// directory is always cleaned up.
///
/// GUID handling: if the newly-installed manifest is one this manager
/// generated itself (no manifest.json in the update), the *old* GUID is
/// kept so existing profile configs referencing this mod keep working. If
/// the update ships its own manifest with its own GUID, that GUID is kept
/// instead (even if it differs from the old one) and the change is logged
/// -- profile configs are not migrated in that case.
pub(crate) async fn install_update_from_archive(
    state: &AppState,
    mods: &mut Vec<Mod>,
    archive_path: &Path,
    existing_guid: Uuid,
) -> TAResult<(Mod, Option<String>)> {
    let old_mod = mods
        .iter()
        .find(|m| m.guid() == existing_guid)
        .cloned()
        .ok_or_else(|| anyhow::anyhow!("mod with GUID {{{}}} not found", existing_guid))
        .into_ta_result()?;
    let old_dir = old_mod.directory.clone();

    let staging_dir = state
        .base_path
        .join(MODS_DIRECTORY)
        .join(format!(".update-{}", Uuid::new_v4()));
    tokio::fs::create_dir_all(&staging_dir).await.into_ta_result()?;

    let staged = stage_update(&staging_dir, archive_path).await;

    let (mut manifest, warning) = match staged {
        Ok(ok) => ok,
        Err(e) => {
            let _ = tokio::fs::remove_dir_all(&staging_dir).await;
            return Err(e);
        }
    };

    let final_guid = if is_local_generated(&manifest) {
        if let Manifest::Legacy(legacy) = &mut manifest {
            legacy.guid = existing_guid;
            // The generated manifest is named after the update's archive
            // file ("CoolMod-1.4.zip" -> "CoolMod-1"); it's the same mod, so
            // keep the name and description the user already knows it by.
            legacy.name = old_mod.name().to_string();
            legacy.description = match &old_mod.manifest {
                Manifest::Legacy(m) => m.description.clone(),
                Manifest::V1(m) => m.description.clone(),
                Manifest::V2(m) => m.description.clone(),
            };
        }
        existing_guid
    } else {
        let new_guid = match &manifest {
            Manifest::Legacy(m) => m.guid,
            Manifest::V1(m) => m.guid,
            Manifest::V2(m) => m.guid,
        };
        if new_guid != existing_guid {
            log::info!(
                "Update for mod {{{}}} ships its own GUID {{{}}}; keeping the new one (profile entries referencing the old GUID will no longer match).",
                existing_guid, new_guid
            );
        }
        new_guid
    };

    // Persist the (possibly GUID-rewritten) manifest into staging before the swap.
    let manifest_data = match serde_json::to_vec_pretty(&manifest) {
        Ok(d) => d,
        Err(e) => {
            let _ = tokio::fs::remove_dir_all(&staging_dir).await;
            return Err(e).into_ta_result();
        }
    };
    if let Err(e) = tokio::fs::write(staging_dir.join(MANIFEST_FILE), manifest_data).await {
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    log::info!("Swapping in updated content for mod {{{}}}...", final_guid);
    let backup_dir = state
        .base_path
        .join(MODS_DIRECTORY)
        .join(format!(".update-backup-{}", Uuid::new_v4()));

    if let Err(e) = crate::fs_util::move_path(&old_dir, &backup_dir).await {
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    if let Err(e) = crate::fs_util::move_path(&staging_dir, &old_dir).await {
        // Roll back: put the old content back where it was.
        let _ = crate::fs_util::move_path(&backup_dir, &old_dir).await;
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    let _ = tokio::fs::remove_dir_all(&backup_dir).await;

    let mut new_mod = Mod {
        manifest,
        directory: old_dir,
        sources: Vec::new(),
    };

    if let Err(e) = new_mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }
    new_mod.resolve_sources().await;

    mods.retain(|m| m.guid() != existing_guid);
    mods.push(new_mod.clone());

    log::info!("Mod {{{}}} updated successfully.", new_mod.guid());
    Ok((new_mod, warning))
}

/// Extract `archive_path` into `staging_dir` and resolve its manifest
/// (generating a local one, with patch-layout auto-detection, if it ships
/// none), without touching anything outside `staging_dir`.
async fn stage_update(staging_dir: &Path, archive_path: &Path) -> TAResult<(Manifest, Option<String>)> {
    let archive = Archive::open(archive_path)?;
    let manifest_file = staging_dir.join(MANIFEST_FILE);
    let name = archive_path
        .file_prefix()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| "update".to_string());

    let (archive, mut manifest) = resolve_manifest(archive, name, manifest_file).await?;

    extract_archive(archive, staging_dir.to_path_buf()).await?;

    let warning = apply_patch_layout(staging_dir, &mut manifest).await.into_ta_result()?;

    Ok((manifest, warning))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::manifest::legacy;
    use std::io::Write;

    fn make_zip(path: &Path, entries: &[(&str, &[u8])]) {
        let file = std::fs::File::create(path).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        let options = zip::write::SimpleFileOptions::default();
        for (name, data) in entries {
            writer.start_file(*name, options).unwrap();
            writer.write_all(data).unwrap();
        }
        writer.finish().unwrap();
    }

    fn patch_file_name() -> String {
        "0123456789abcdef.patch_0".to_string()
    }

    async fn make_existing_mod(base: &Path, name: &str) -> (Uuid, PathBuf) {
        let mod_dir = base.join(MODS_DIRECTORY).join(name);
        tokio::fs::create_dir_all(&mod_dir).await.unwrap();
        tokio::fs::write(mod_dir.join(patch_file_name()), b"old content")
            .await
            .unwrap();

        let mut guid_bytes = [0u8; 16];
        guid_bytes[..5].copy_from_slice(b"LOCAL");
        guid_bytes[5] = 1;
        let guid = Uuid::from_bytes(guid_bytes);

        let manifest = Manifest::Legacy(legacy::Manifest {
            guid,
            name: name.to_string(),
            description: String::new(),
            icon_path: None,
            options: None,
        });
        let data = serde_json::to_vec_pretty(&manifest).unwrap();
        tokio::fs::write(mod_dir.join(MANIFEST_FILE), data)
            .await
            .unwrap();

        (guid, mod_dir)
    }

    #[tokio::test]
    async fn ensure_mods_loaded_marks_first_run_as_loaded() {
        let base = tempfile::tempdir().unwrap();
        let mut state_mods = None;
        let mods = ensure_mods_loaded(&mut state_mods, base.path()).await.unwrap();
        assert!(mods.is_empty());
        assert!(base.path().join(MODS_DIRECTORY).is_dir());
        // Previously the empty first-run list was returned but never stored,
        // so installs failed with "mods not read" until get_mods ran again.
        assert!(state_mods.is_some());
    }

    #[tokio::test]
    async fn ensure_mods_loaded_reads_existing_mods_once() {
        let base = tempfile::tempdir().unwrap();
        let (guid, _) = make_existing_mod(base.path(), "CoolMod").await;
        let mut state_mods = None;
        let mods = ensure_mods_loaded(&mut state_mods, base.path()).await.unwrap();
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), guid);
    }

    #[tokio::test]
    async fn install_update_keeps_old_guid_when_new_manifest_is_local_generated() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: old_dir.clone(),
            sources: Vec::new(),
        }];

        let update_zip = base.path().join("update.zip");
        make_zip(&update_zip, &[(&patch_file_name(), b"new content")]);

        let state = AppState::new(base.path().to_path_buf());
        let (updated, warning) = install_update_from_archive(&state, &mut mods, &update_zip, old_guid)
            .await
            .unwrap();

        assert!(warning.is_none());
        assert_eq!(updated.guid(), old_guid);
        assert_eq!(updated.name(), "CoolMod", "an update keeps the mod's name, not the archive's");
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), old_guid);

        let content = tokio::fs::read(old_dir.join(patch_file_name())).await.unwrap();
        assert_eq!(content, b"new content");
    }

    #[tokio::test]
    async fn install_update_keeps_new_guid_when_manifest_declares_its_own() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, _old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: base.path().join(MODS_DIRECTORY).join("CoolMod"),
            sources: Vec::new(),
        }];

        let new_manifest = serde_json::json!({
            "Guid": "11111111-1111-1111-1111-111111111111",
            "Name": "CoolMod",
            "Description": "shipped manifest",
        });
        let update_zip = base.path().join("update.zip");
        make_zip(
            &update_zip,
            &[
                (MANIFEST_FILE, serde_json::to_vec_pretty(&new_manifest).unwrap().as_slice()),
                (&patch_file_name(), b"new content"),
            ],
        );

        let state = AppState::new(base.path().to_path_buf());
        let (updated, _warning) = install_update_from_archive(&state, &mut mods, &update_zip, old_guid)
            .await
            .unwrap();

        let new_guid = Uuid::parse_str("11111111-1111-1111-1111-111111111111").unwrap();
        assert_eq!(updated.guid(), new_guid);
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), new_guid);
    }

    #[tokio::test]
    async fn install_update_leaves_old_mod_untouched_on_failure() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: old_dir.clone(),
            sources: Vec::new(),
        }];

        // Not a real archive: Archive::open will fail on the unsupported/invalid content.
        let bad_path = base.path().join("update.exe");
        tokio::fs::write(&bad_path, b"not an archive").await.unwrap();

        let state = AppState::new(base.path().to_path_buf());
        let result = install_update_from_archive(&state, &mut mods, &bad_path, old_guid).await;

        assert!(result.is_err());
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), old_guid);
        assert!(old_dir.join(patch_file_name()).is_file());
        let content = tokio::fs::read(old_dir.join(patch_file_name())).await.unwrap();
        assert_eq!(content, b"old content");
    }

    #[tokio::test]
    async fn mod_image_resolves_backslashes_and_casing_inside_the_mod() {
        let base = tempfile::tempdir().unwrap();
        let mod_dir = base.path().join("mods").join("Cool Mod");
        tokio::fs::create_dir_all(mod_dir.join("Images")).await.unwrap();
        tokio::fs::write(mod_dir.join("Images").join("Icon.png"), b"png").await.unwrap();
        tokio::fs::write(base.path().join("outside.png"), b"png").await.unwrap();

        for written in ["Images/Icon.png", "images\\icon.PNG", ".\\Images\\Icon.png"] {
            let got = resolve_mod_image_path(base.path(), &mod_dir, written).await;
            assert_eq!(got, Some(mod_dir.join("Images").join("Icon.png")), "{written}");
        }
        assert_eq!(resolve_mod_image_path(base.path(), &mod_dir, "missing.png").await, None);
        assert_eq!(resolve_mod_image_path(base.path(), &mod_dir, "Images").await, None, "a folder isn't an image");
        // `..` is dropped by fix_path_casing, so this can't reach outside.png.
        assert_eq!(resolve_mod_image_path(base.path(), &mod_dir, "../../outside.png").await, None);
        // Only folders inside mods/ are answered for.
        assert_eq!(resolve_mod_image_path(base.path(), base.path(), "outside.png").await, None);
        assert_eq!(resolve_mod_image_path(base.path(), &base.path().join("mods"), "Cool Mod/Images/Icon.png").await, None);
    }

    /// (files, total bytes) under `dir`, not following symlinks.
    fn tree_size(dir: &Path) -> (usize, u64) {
        let mut out = (0, 0);
        for entry in std::fs::read_dir(dir).unwrap() {
            let entry = entry.unwrap();
            let ft = entry.file_type().unwrap();
            if ft.is_dir() {
                let (n, b) = tree_size(&entry.path());
                out = (out.0 + n, out.1 + b);
            } else if ft.is_file() {
                out = (out.0 + 1, out.1 + entry.metadata().unwrap().len());
            }
        }
        out
    }

    /// DDMM's data folder with mod folders already sitting in `mods/`
    /// without a manifest.json -- e.g. a portable copy of DDMM dropped next
    /// to an existing `mods/` folder full of unpacked mods.
    fn storage_with_loose_mods(base: &Path) -> PathBuf {
        let storage = base.join(MODS_DIRECTORY);
        for name in ["ModA", "ModB"] {
            std::fs::create_dir_all(storage.join(name)).unwrap();
            std::fs::write(storage.join(name).join(patch_file_name()), vec![7u8; 1000]).unwrap();
        }
        storage
    }

    fn err_text<T: std::fmt::Debug>(r: TAResult<T>) -> String {
        format!("{:?}", r.unwrap_err())
    }

    /// The reported bug: "Add folder" on the mod storage folder itself used
    /// to copy it into `mods/mods`, and the copy kept re-reading what it had
    /// just written: `mods/mods/mods/...`, a full copy of every mod at every
    /// level, until the path got too long or the disk filled up.
    #[tokio::test]
    async fn adding_the_mod_storage_folder_is_refused_without_copying() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let before = tree_size(&storage);
        let mut mods = Vec::new();

        let msg = err_text(install_from_folder(base.path(), &mut mods, &storage).await);

        assert!(msg.contains("own mod storage"), "{msg}");
        assert!(!storage.join("mods").exists(), "must not nest a copy");
        assert_eq!(tree_size(&storage), before);
        assert!(mods.is_empty());
    }

    /// Same, when the picked folder is DDMM's data folder (it contains
    /// `mods/`), e.g. a portable install living in the user's mod folder.
    #[tokio::test]
    async fn adding_a_folder_that_contains_the_mod_storage_is_refused() {
        let root = tempfile::tempdir().unwrap();
        let base = root.path().join("MyMods");
        let storage = storage_with_loose_mods(&base);
        let before = tree_size(&base);
        let mut mods = Vec::new();

        let msg = err_text(install_from_folder(&base, &mut mods, &base).await);

        assert!(msg.contains("copy the folder into itself"), "{msg}");
        assert!(!storage.join("MyMods").exists());
        assert_eq!(tree_size(&base), before);
    }

    #[tokio::test]
    async fn adding_the_mod_storage_via_dotdot_is_refused() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let before = tree_size(&storage);
        let mut mods = Vec::new();

        let roundabout = storage.join("ModA").join("..");
        assert!(install_from_folder(base.path(), &mut mods, &roundabout).await.is_err());
        assert_eq!(tree_size(&storage), before);
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn adding_the_mod_storage_via_a_symlink_is_refused() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let before = tree_size(&storage);
        let elsewhere = tempfile::tempdir().unwrap();
        let link = elsewhere.path().join("my mods");
        std::os::unix::fs::symlink(&storage, &link).unwrap();
        let mut mods = Vec::new();

        assert!(install_from_folder(base.path(), &mut mods, &link).await.is_err());
        assert!(!storage.join("my mods").exists());
        assert_eq!(tree_size(&storage), before);
    }

    #[cfg(any(windows, target_os = "macos"))]
    #[tokio::test]
    async fn adding_the_mod_storage_spelled_in_other_case_is_refused() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let before = tree_size(&storage);
        let mut mods = Vec::new();

        assert!(install_from_folder(base.path(), &mut mods, &base.path().join("MODS")).await.is_err());
        assert_eq!(tree_size(&storage), before);
    }

    #[tokio::test]
    async fn adding_a_folder_deep_inside_a_stored_mod_is_refused() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let inner = storage.join("ModA").join("Options");
        std::fs::create_dir_all(&inner).unwrap();
        std::fs::write(inner.join(patch_file_name()), b"x").unwrap();
        let before = tree_size(&storage);
        let mut mods = Vec::new();

        let msg = err_text(install_from_folder(base.path(), &mut mods, &inner).await);

        assert!(msg.contains("inside a mod folder"), "{msg}");
        assert_eq!(tree_size(&storage), before);
    }

    /// A mod folder already directly in the storage is adopted where it is:
    /// no copy, nothing deleted, just a manifest so it shows up.
    #[tokio::test]
    async fn adding_a_loose_folder_in_the_storage_adopts_it_in_place() {
        let base = tempfile::tempdir().unwrap();
        let storage = storage_with_loose_mods(base.path());
        let mut mods = Vec::new();

        let (r#mod, warning) = install_from_folder(base.path(), &mut mods, &storage.join("ModA")).await.unwrap();

        assert!(warning.is_none());
        assert_eq!(r#mod.name(), "ModA");
        assert_eq!(r#mod.directory, storage.join("ModA"));
        assert!(storage.join("ModA").join(MANIFEST_FILE).is_file());
        assert!(storage.join("ModA").join(patch_file_name()).is_file());
        assert_eq!(std::fs::read_dir(&storage).unwrap().count(), 2, "no copy was made");
        assert_eq!(mods.len(), 1);

        // And it loads on the next start like any other mod.
        let mut state_mods = None;
        let loaded = ensure_mods_loaded(&mut state_mods, base.path()).await.unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].guid(), r#mod.guid());

        // Adding it a second time is an error, and deletes nothing.
        let msg = err_text(install_from_folder(base.path(), &mut mods, &storage.join("ModA")).await);
        assert!(msg.contains("already installed"), "{msg}");
        assert!(storage.join("ModA").join(patch_file_name()).is_file());
        assert!(storage.join("ModA").join(MANIFEST_FILE).is_file());
    }

    #[tokio::test]
    async fn adding_a_folder_outside_the_storage_still_copies_it() {
        let base = tempfile::tempdir().unwrap();
        let elsewhere = tempfile::tempdir().unwrap();
        let src = elsewhere.path().join("Cool Mod");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(src.join(patch_file_name()), b"p").unwrap();
        let mut mods = Vec::new();

        let (r#mod, _) = install_from_folder(base.path(), &mut mods, &src).await.unwrap();

        let dst = base.path().join(MODS_DIRECTORY).join("Cool Mod");
        assert_eq!(r#mod.directory, dst);
        assert!(dst.join(patch_file_name()).is_file());
        assert!(src.join(patch_file_name()).is_file(), "source untouched");
        assert!(!src.join(MANIFEST_FILE).exists(), "source untouched");
    }

    /// A copy that fails partway must not leave a half-copied mod behind.
    #[cfg(unix)]
    #[tokio::test]
    async fn a_folder_copy_that_fails_partway_is_cleaned_up() {
        use std::os::unix::fs::PermissionsExt;

        let base = tempfile::tempdir().unwrap();
        let elsewhere = tempfile::tempdir().unwrap();
        let src = elsewhere.path().join("Broken");
        std::fs::create_dir_all(src.join("Options")).unwrap();
        std::fs::write(src.join(patch_file_name()), b"p").unwrap();
        let unreadable = src.join("Options").join(patch_file_name());
        std::fs::write(&unreadable, b"secret").unwrap();
        std::fs::set_permissions(&unreadable, std::fs::Permissions::from_mode(0o000)).unwrap();
        if std::fs::read(&unreadable).is_ok() {
            // Running as root: permissions can't make the copy fail.
            return;
        }
        let mut mods = Vec::new();

        let result = install_from_folder(base.path(), &mut mods, &src).await;

        std::fs::set_permissions(&unreadable, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(result.is_err());
        assert!(!base.path().join(MODS_DIRECTORY).join("Broken").exists());
        assert!(mods.is_empty());
    }

    /// An archive picked from inside the folder it would be installed into
    /// (`mods/Foo/Foo.zip`, with `mods/Foo` not yet a mod) used to have that
    /// folder, archive included, deleted to make room.
    #[tokio::test]
    async fn an_archive_inside_its_own_install_folder_is_refused_and_kept() {
        let base = tempfile::tempdir().unwrap();
        let target = base.path().join(MODS_DIRECTORY).join("Foo");
        std::fs::create_dir_all(&target).unwrap();
        let zip = target.join("Foo.zip");
        make_zip(&zip, &[(&patch_file_name(), b"p")]);
        let state = AppState::new(base.path().to_path_buf());
        let mut mods = Vec::new();

        let msg = err_text(install_from_archive(&state, &mut mods, &zip).await);

        assert!(msg.contains("inside"), "{msg}");
        assert!(zip.is_file(), "the picked archive must survive");
    }
}
