use crate::{
    archive::Archive,
    download,
    models::{
        manifest::{legacy, Manifest, Source},
        Mod,
    },
    sources,
    utils::{copy_dir_recursive, detect_patch_layout, PatchLayout},
    AppState,
};
use anyhow_tauri::{IntoTAResult, TAResult};
use rand::{rngs::SysRng, TryRng};
use serde::Serialize;
use std::{collections::HashSet, path::{Path, PathBuf}};
use tauri::State;
use uuid::Uuid;

const MODS_DIRECTORY: &'static str = "mods/";
const MANIFEST_FILE: &'static str = "manifest.json";
const NO_PATCH_FILES_WARNING: &str = "no Helldivers 2 patch files found in this archive";

/// The JSON shape returned by every install command: a [`Mod`] plus an
/// optional, non-fatal warning (currently only "no Helldivers 2 patch files
/// found").
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "PascalCase")]
pub struct InstalledMod {
    #[serde(flatten)]
    pub r#mod: Mod,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
}

/// A manifest counts as "generated by us" (as opposed to one an author
/// shipped) exactly when it's the `LOCAL`-prefixed legacy manifest
/// `generate_local_manifest` produces. Only those are safe to rewrite with
/// an auto-detected `Options` list -- an author's own manifest.json is
/// never touched.
fn is_local_generated(manifest: &Manifest) -> bool {
    matches!(manifest, Manifest::Legacy(m) if m.guid.as_bytes().get(..5) == Some(b"LOCAL"))
}

/// After extraction/copy, if (and only if) the manifest was generated by us
/// because the mod shipped no `manifest.json` of its own, look for where
/// the actual Helldivers 2 patch files ended up and, if they're not at the
/// mod root, fill in `Options` (persisting the rewritten manifest.json) so
/// deploy and the existing option picker find them without any further
/// user action. Returns a non-fatal warning if no patch files were found
/// anywhere.
async fn apply_patch_layout(mod_dir: &Path, manifest: &mut Manifest) -> anyhow::Result<Option<String>> {
    if !is_local_generated(manifest) {
        return Ok(None);
    }

    let layout = detect_patch_layout(mod_dir).await?;

    match layout {
        PatchLayout::RootHasFiles => Ok(None),
        PatchLayout::Options(paths) => {
            if let Manifest::Legacy(legacy) = manifest {
                legacy.options = Some(paths);
            }
            let manifest_file = mod_dir.join(MANIFEST_FILE);
            let data = serde_json::to_vec_pretty(manifest)?;
            tokio::fs::write(manifest_file, data).await?;
            Ok(None)
        }
        PatchLayout::NoneFound => Ok(Some(NO_PATCH_FILES_WARNING.to_string())),
    }
}

#[allow(dead_code)]
trait ZipResult<S, E, T> {
    fn zip(self, other: Result<T, E>) -> Result<(S, T), E>;
    fn zip_value(self, other: T) -> Result<(S, T), E>;
}

impl<S, E, T> ZipResult<S, E, T> for Result<S, E> {
    fn zip(self, other: Result<T, E>) -> Result<(S, T), E> {
        match (self, other) {
            (Ok(a), Ok(b)) => Ok((a, b)),
            (Err(e), Ok(_)) => Err(e),
            (Ok(_), Err(e)) => Err(e),
            (Err(e), Err(_)) => Err(e),
        }
    }

    fn zip_value(self, other: T) -> Result<(S, T), E> {
        match self {
            Ok(s) => Ok((s, other)),
            Err(e) => Err(e)
        }
    }
}

#[tauri::command]
pub async fn get_mods(state: State<'_, AppState>) -> TAResult<Vec<Mod>> {
    let mut state_mods = state.mods.lock().await;
    log::info!("Loading mods...");
    let mods = ensure_mods_loaded(&mut state_mods, &state.base_path).await?;
    Ok(mods.clone())
}

/// Read every installed mod from disk into `state_mods` the first time it's
/// needed (a no-op once loaded) and return it. Shared by `get_mods` and by
/// the browser bridge, which can receive an install before the frontend
/// has ever called `get_mods` -- e.g. a first run still on the Settings
/// page, or DDMM just launched by the native-messaging host.
pub(crate) async fn ensure_mods_loaded<'a>(
    state_mods: &'a mut Option<Vec<Mod>>,
    base_path: &Path,
) -> TAResult<&'a mut Vec<Mod>> {
    if state_mods.is_some() {
        log::info!("Mods already loaded.");
        return Ok(state_mods.as_mut().unwrap());
    }

    let mods_dir = base_path.join(MODS_DIRECTORY);
    let mut mods = Vec::new();
    if !mods_dir.is_dir() {
        // First run: nothing installed yet. Still record the (empty) list
        // as loaded, or every install command would fail with "mods not
        // read" until something called get_mods a second time.
        tokio::fs::create_dir_all(&mods_dir).await.into_ta_result()?;
    } else {
        let mut mods_dir = tokio::fs::read_dir(mods_dir).await.into_ta_result()?;
        while let Some(entry) = mods_dir.next_entry().await.into_ta_result()? {
            let mod_dir = entry.path();

            let manifest_file = mod_dir.join(MANIFEST_FILE);
            if !manifest_file.is_file() {
                continue;
            }

            let manifest_data = tokio::fs::read(manifest_file).await.into_ta_result()?;
            let manifest: Manifest = serde_json::from_slice(&manifest_data).into_ta_result()?;

            let mut r#mod = Mod {
                manifest,
                directory: mod_dir,
                sources: Vec::new(),
            };
            r#mod.normalize_paths().await?;
            r#mod.resolve_sources().await;

            mods.push(r#mod);
        }
    }

    log::info!("Mods loaded.");
    Ok(state_mods.insert(mods))
}

#[tauri::command]
pub async fn delete_mod(state: State<'_, AppState>, guid: Uuid) -> TAResult<()> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    log::info!("Deleting mod \"{}\"...", guid);

    if let Some(i) = mods.iter().position(|m| m.guid() == guid) {
        let r#mod = mods.remove(i);
        log::info!("Mod removed form registry.");

        log::info!("Deleting files...");
        tokio::fs::remove_dir_all(r#mod.directory).await.into_ta_result()?;
        
        log::info!("Mod deletion complete.");
        Ok(())
    } else {
        anyhow_tauri::bail!("mod with GUID {{{}}} not found", guid);
    }
}

#[tauri::command]
pub async fn add_mod(state: State<'_, AppState>, archive_file: PathBuf) -> TAResult<InstalledMod> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    let (r#mod, warning) = install_from_archive(&state, mods, &archive_file).await?;
    Ok(InstalledMod { r#mod, warning })
}

/// Shared core of `add_mod`: prepares the mod directory, resolves the
/// manifest (from the archive if present, generating a local one
/// otherwise), extracts, and registers the mod.
///
/// Takes the already-locked mods vector rather than `State` directly so it
/// can be called both from a `#[tauri::command]` that holds the lock for a
/// single install, and from callers (like `add_paths`) that lock once per
/// item without ever calling back into another `#[tauri::command]` while
/// holding the mutex.
pub(crate) async fn install_from_archive(state: &AppState, mods: &mut Vec<Mod>, archive_file: &Path) -> TAResult<(Mod, Option<String>)> {
    log::info!("Adding mod from {:?}...", archive_file);

    log::debug!("Opening archive...");
    let archive = Archive::open(archive_file)?;

    log::debug!("Obtaining name...");
    let name = archive_file
        .file_prefix()
        .unwrap()
        .to_str()
        .map(str::to_string)
        .ok_or(anyhow::anyhow!("file name conversion failed"))?;

    log::info!("Resolving mod directory...");
    let mut mod_dir = state.base_path.join(MODS_DIRECTORY);
    mod_dir.push(&name);

    log::info!("Preparing mod directory...");
    let manifest_file = mod_dir.join(MANIFEST_FILE);
    prepare_mod_dir(mod_dir.clone(), manifest_file.clone(), name.clone()).await.into_ta_result()?;

    // From here on `mod_dir` is ours (prepare_mod_dir just created it), so
    // a failure must remove it again: a half-written directory with a
    // manifest.json would otherwise show up as an empty "ghost" mod on the
    // next launch and block retrying the same file with "mod directory
    // already exists" (e.g. after an archive was rejected as unsafe).
    let prepared: TAResult<(Mod, Option<String>)> = async {
        log::info!("Resolving manifest...");
        let (archive, manifest) = resolve_manifest(archive, name.clone(), manifest_file.clone()).await.into_ta_result()?;

        let mut r#mod = Mod {
            manifest,
            directory: mod_dir.clone(),
            sources: Vec::new(),
        };

        log::info!("Checking for duplicate...");
        if mods.iter().any(|m| m.guid() == r#mod.guid()) {
            return anyhow::anyhow!("mod with GUID {{{}}} already exists", r#mod.guid())
                .into_ta_result();
        }

        log::info!("Extracting archive...");
        extract_archive(archive, mod_dir.clone()).await?;

        log::debug!("Detecting patch file layout...");
        let warning = apply_patch_layout(&mod_dir, &mut r#mod.manifest).await.into_ta_result()?;
        Ok((r#mod, warning))
    }
    .await;
    let (mut r#mod, warning) = match prepared {
        Ok(v) => v,
        Err(e) => {
            if let Err(cleanup) = tokio::fs::remove_dir_all(&mod_dir).await {
                log::error!("Failed to clean up {:?} after a failed install: {}", mod_dir, cleanup);
            }
            return Err(e);
        }
    };

    log::debug!("Normalizing paths...");
    if let Err(e) = r#mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }

    r#mod.resolve_sources().await;

    mods.push(r#mod.clone());
    log::info!("Mod successfully added.");
    Ok((r#mod, warning))
}

#[tauri::command]
pub async fn add_mods(state: State<'_, AppState>, archive_files: Vec<PathBuf>) -> TAResult<Vec<TAResult<InstalledMod>>> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    log::info!("Adding mods from:",);
    for archive_file in &archive_files {
        log::info!(" - {:?}", archive_file);
    }
    
    log::debug!("Opening archives...");
    let data = archive_files
        .iter()
        .map(|archive_file| Archive::open(archive_file).into_ta_result())
        .collect::<Vec<_>>();

    log::debug!("Obtaining names...");
    let data = archive_files
        .iter()
        .cloned()
        .zip(data)
        .map(|(archive_file, result)| {
            result
                .zip_value(archive_file)
                .map(|(archive, archive_file)| {
                    let name = archive_file
                        .file_prefix()
                        .unwrap()
                        .to_str()
                        .map(str::to_string)
                        .ok_or(anyhow::anyhow!("file name conversion failed"))
                        .into_ta_result()?;
                    Ok((archive, name))
                })
                .flatten()
        })
        .collect::<Vec<_>>();

    log::info!("Resolving mod directories...");
    let data = data
        .into_iter()
        .map(|result| {
            result
                .map(|(archive, name)| {
                    let mut mod_dir = state.base_path.join(MODS_DIRECTORY);
                    mod_dir.push(&name);
                    let manifest_file = mod_dir.join(MANIFEST_FILE);
                    (archive, name, mod_dir, manifest_file)
                })
        })
        .collect::<Vec<_>>();

    log::info!("Preparing mod directories...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, name, mod_dir, manifest_file)) => {
                    prepare_mod_dir(mod_dir.clone(), manifest_file.clone(), name.clone()).await?;
                    Ok((archive, name, mod_dir, manifest_file))
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    log::info!("Resolving manifests...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, name, mod_dir, manifest_file)) => {
                    let (archive, manifest) = resolve_manifest(archive, name, manifest_file).await?;
                    Ok((archive, mod_dir, manifest))
                }
                Err(e) => Err(e)
            }
        })
    ).await;
    
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, mod_dir, manifest)| {
                let r#mod = Mod {
                    manifest,
                    directory: mod_dir,
                    sources: Vec::new(),
                };
                (archive, r#mod)
            })
        })
        .collect::<Vec<_>>();
    
    log::info!("Checking for duplicates...");
    let mut guids: HashSet<Uuid> = mods.iter().map(|m| m.guid()).collect();
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, r#mod)| {
                let guid = r#mod.guid();
                if guids.insert(guid) {
                    Ok((archive, r#mod))
                } else {
                    anyhow_tauri::bail!("mod with GUID {{{}}} already exists", guid)
                }
            })
            .flatten()
        })
        .collect::<Vec<_>>();

    let mut guids = HashSet::<Uuid>::new();
    let data = data
        .into_iter()
        .map(|result| {
            result.map(|(archive, r#mod)| {
                let guid = r#mod.guid();
                if guids.insert(guid) {
                    Ok((archive, r#mod))
                } else {
                    anyhow_tauri::bail!("already adding mod with GUID {{{}}}", guid)
                }
            })
            .flatten()
        })
        .collect::<Vec<_>>();

    log::info!("Extracting archives...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok((archive, r#mod)) => {
                    extract_archive(archive, r#mod.directory.clone()).await?;
                    Ok(r#mod)
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    log::debug!("Detecting patch file layouts and normalizing paths...");
    let data = futures::future::join_all(
        data.into_iter().map(|result| async {
            match result {
                Ok(mut r#mod) => {
                    let warning = match apply_patch_layout(&r#mod.directory.clone(), &mut r#mod.manifest).await {
                        Ok(w) => w,
                        Err(e) => {
                            log::error!("Patch layout detection failed for \"{}\": {}", r#mod.guid(), e);
                            None
                        }
                    };
                    if let Err(e) = r#mod.normalize_paths().await {
                        log::error!("Path normalization failed for \"{}\": {}", r#mod.guid(), e);
                    }
                    r#mod.resolve_sources().await;
                    Ok((r#mod, warning))
                }
                Err(e) => Err(e)
            }
        })
    ).await;

    for (r#mod, _) in data.iter().flatten() {
        mods.push(r#mod.clone());
    }

    log::info!("Adding complete.");
    for (p, r) in archive_files.iter().zip(&data) {
        if let Err(e) = r {
            log::info!(" - {:?} : Err -> {}", p, e);
        } else {
            log::info!(" - {:?} : Ok", p);
        }
    }

    let data = data
        .into_iter()
        .map(|result| result.map(|(r#mod, warning)| InstalledMod { r#mod, warning }))
        .collect::<Vec<_>>();

    Ok(data)
}

async fn prepare_mod_dir(mod_dir: PathBuf, manifest_file: PathBuf, name: String) -> TAResult<()> {
    if tokio::fs::try_exists(&mod_dir).await.into_ta_result()? {
        if tokio::fs::try_exists(&manifest_file).await.into_ta_result()? {
            return anyhow::anyhow!("mod directory \"{}\" already exists", name).into_ta_result();
        } else {
            tokio::fs::remove_dir_all(&mod_dir).await.into_ta_result()?;
        }
    }
    tokio::fs::create_dir_all(&mod_dir).await.into_ta_result()
}

/// Generate the same "no manifest present" local legacy manifest, whether
/// the mod came from an archive with no `manifest.json`, or a plain folder
/// with no `manifest.json`.
fn generate_local_manifest(name: String) -> anyhow::Result<Manifest> {
    let mut guid = [0u8; 16];
    guid[..5].copy_from_slice(b"LOCAL");
    SysRng.try_fill_bytes(&mut guid[5..])?;

    Ok(Manifest::Legacy(legacy::Manifest {
        guid: Uuid::from_bytes(guid),
        name,
        description: String::new(),
        icon_path: None,
        options: None,
    }))
}

async fn resolve_manifest(mut archive: Archive, name: String, manifest_file: PathBuf) -> TAResult<(Archive, Manifest)> {
    if archive.has_path(MANIFEST_FILE)? {
        let manifest_data = archive.read_path(MANIFEST_FILE)?;
        let manifest = serde_json::from_slice(&manifest_data).into_ta_result()?;
        Ok((archive, manifest))
    } else {
        let manifest = generate_local_manifest(name).into_ta_result()?;

        let manifest_data = serde_json::to_vec_pretty(&manifest).into_ta_result()?;
        tokio::fs::write(&manifest_file, manifest_data)
            .await
            .into_ta_result()?;

        Ok((archive, manifest))
    }
}

/// Same idea as [`resolve_manifest`], but for a plain folder install: read
/// `manifest.json` from the source folder if present, otherwise generate a
/// local one and write it straight into the (already-created) destination
/// mod directory.
async fn resolve_manifest_for_dir(source_dir: &Path, name: String, manifest_file: PathBuf) -> TAResult<Manifest> {
    let source_manifest = source_dir.join(MANIFEST_FILE);
    if tokio::fs::try_exists(&source_manifest).await.into_ta_result()? {
        let manifest_data = tokio::fs::read(&source_manifest).await.into_ta_result()?;
        let manifest: Manifest = serde_json::from_slice(&manifest_data).into_ta_result()?;
        Ok(manifest)
    } else {
        let manifest = generate_local_manifest(name).into_ta_result()?;

        let manifest_data = serde_json::to_vec_pretty(&manifest).into_ta_result()?;
        tokio::fs::write(&manifest_file, manifest_data)
            .await
            .into_ta_result()?;

        Ok(manifest)
    }
}

async fn extract_archive(mut archive: Archive, mod_dir: PathBuf) -> TAResult<()> {
    tokio::task::spawn_blocking(move || archive.extract_to(mod_dir).into_ta_result()).await.into_ta_result()?
}

/// Install a mod from a plain, already-unpacked folder: `folder` becomes the
/// mod's source, its `manifest.json` is used if present (otherwise a local
/// one is generated), and its contents are copied (not moved, symlinks not
/// followed) into the managed mod directory.
///
/// Mirrors [`install_from_archive`]'s locking contract: takes the
/// already-locked mods vector, never locks anything itself.
async fn install_from_folder(state: &AppState, mods: &mut Vec<Mod>, folder: &Path) -> TAResult<(Mod, Option<String>)> {
    log::info!("Adding mod from folder {:?}...", folder);

    if !folder.is_dir() {
        return anyhow::anyhow!("path is not a directory").into_ta_result();
    }

    let name = folder
        .file_name()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .ok_or(anyhow::anyhow!("folder name conversion failed"))?;

    log::info!("Resolving mod directory...");
    let mut mod_dir = state.base_path.join(MODS_DIRECTORY);
    mod_dir.push(&name);

    log::info!("Preparing mod directory...");
    let manifest_file = mod_dir.join(MANIFEST_FILE);
    prepare_mod_dir(mod_dir.clone(), manifest_file.clone(), name.clone()).await.into_ta_result()?;

    let result = install_from_folder_inner(mods, folder, &name, &mod_dir, &manifest_file).await;

    if result.is_err() {
        let _ = tokio::fs::remove_dir_all(&mod_dir).await;
    }

    result
}

async fn install_from_folder_inner(
    mods: &mut Vec<Mod>,
    folder: &Path,
    name: &str,
    mod_dir: &Path,
    manifest_file: &Path,
) -> TAResult<(Mod, Option<String>)> {
    log::info!("Resolving manifest...");
    let manifest = resolve_manifest_for_dir(folder, name.to_string(), manifest_file.to_path_buf()).await?;

    let mut r#mod = Mod {
        manifest,
        directory: mod_dir.to_path_buf(),
        sources: Vec::new(),
    };

    log::info!("Checking for duplicate...");
    if mods.iter().any(|m| m.guid() == r#mod.guid()) {
        return anyhow::anyhow!("mod with GUID {{{}}} already exists", r#mod.guid())
            .into_ta_result();
    }

    log::info!("Copying folder contents...");
    copy_dir_recursive(folder, mod_dir, &[sources::ORIGIN_SIDECAR_FILE])
        .await
        .into_ta_result()?;

    log::debug!("Detecting patch file layout...");
    let warning = apply_patch_layout(mod_dir, &mut r#mod.manifest).await.into_ta_result()?;

    log::debug!("Normalizing paths...");
    if let Err(e) = r#mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }

    r#mod.resolve_sources().await;

    mods.push(r#mod.clone());
    log::info!("Mod successfully added.");
    Ok((r#mod, warning))
}

#[tauri::command]
pub async fn add_mod_folder(state: State<'_, AppState>, folder: PathBuf) -> TAResult<InstalledMod> {
    let mut mods = state.mods.lock().await;
    if mods.is_none() {
        return anyhow::anyhow!("mods not read").into_ta_result();
    }
    let mods = mods.as_mut().unwrap();

    let (r#mod, warning) = install_from_folder(&state, mods, &folder).await?;
    Ok(InstalledMod { r#mod, warning })
}

/// Install any mix of archive files and plain folders in one go, dispatching
/// each path to the right installer. Each path locks the mods mutex
/// independently, so one item's failure never blocks the rest and nothing
/// ever nests a lock inside another lock.
#[tauri::command]
pub async fn add_paths(state: State<'_, AppState>, paths: Vec<PathBuf>) -> TAResult<Vec<TAResult<InstalledMod>>> {
    log::info!("Adding mods from {} path(s)...", paths.len());

    let mut results = Vec::with_capacity(paths.len());
    for path in paths {
        let is_dir = tokio::fs::metadata(&path)
            .await
            .map(|m| m.is_dir())
            .unwrap_or(false);

        let result = if is_dir {
            let mut mods = state.mods.lock().await;
            match mods.as_mut() {
                Some(mods) => install_from_folder(&state, mods, &path).await,
                None => anyhow::anyhow!("mods not read").into_ta_result(),
            }
        } else {
            let mut mods = state.mods.lock().await;
            match mods.as_mut() {
                Some(mods) => install_from_archive(&state, mods, &path).await,
                None => anyhow::anyhow!("mods not read").into_ta_result(),
            }
        };

        results.push(result.map(|(r#mod, warning)| InstalledMod { r#mod, warning }));
    }

    Ok(results)
}

/// Install a mod by downloading an archive from a direct `https://` URL
/// first (into a throwaway temp directory), then running it through the
/// same install path as a locally picked archive file. Records where the
/// mod came from in a `.hd2mm-origin.json` sidecar next to the mod, without
/// ever touching the author's own `manifest.json`.
#[tauri::command]
pub async fn add_mod_from_url(state: State<'_, AppState>, url: String) -> TAResult<InstalledMod> {
    log::info!("Downloading mod from {}...", url);

    let downloaded = download::download_archive(&url).await.into_ta_result()?;

    let install_result = {
        let mut mods = state.mods.lock().await;
        match mods.as_mut() {
            Some(mods) => install_from_archive(&state, mods, &downloaded.path).await,
            None => anyhow::anyhow!("mods not read").into_ta_result(),
        }
    };

    // The staged download (and its throwaway parent directory) is no longer
    // needed either way -- the archive contents were copied out on success.
    let _ = tokio::fs::remove_dir_all(&downloaded.temp_dir).await;

    let (mut r#mod, warning) = install_result?;

    log::info!("Recording install origin...");
    let origin_source = sources::source_from_page_url(&url).unwrap_or_else(|| Source {
        provider: sources::provider_from_url(&url),
        id: None,
        url: Some(url.clone()),
        version: None,
    });
    if let Err(e) = sources::write_origin_sidecar(&r#mod.directory, vec![origin_source]).await {
        log::error!("Failed to write origin sidecar: {}", e);
    }

    r#mod.resolve_sources().await;

    {
        let mut mods = state.mods.lock().await;
        if let Some(mods) = mods.as_mut() {
            if let Some(existing) = mods.iter_mut().find(|m| m.guid() == r#mod.guid()) {
                *existing = r#mod.clone();
            }
        }
    }

    Ok(InstalledMod { r#mod, warning })
}
/// Install `archive_path` as an update of the existing mod `existing_guid`,
/// used by both the browser handoff and the "Update from {site}" flow.
///
/// The new content is fully staged (extracted, manifest resolved, patch
/// layout detected) in a throwaway directory under the mods folder before
/// anything about the existing mod is touched. Only once that succeeds is
/// the old mod directory swapped out for the new one; on any failure before
/// the swap the old mod is left completely untouched, and the staging
/// directory is always cleaned up.
///
/// GUID handling: if the newly-installed manifest is one this manager
/// generated itself (no manifest.json in the update), the *old* GUID is
/// kept so existing profile configs referencing this mod keep working. If
/// the update ships its own manifest with its own GUID, that GUID is kept
/// instead (even if it differs from the old one) and the change is logged
/// -- profile configs are not migrated in that case.
pub(crate) async fn install_update_from_archive(
    state: &AppState,
    mods: &mut Vec<Mod>,
    archive_path: &Path,
    existing_guid: Uuid,
) -> TAResult<(Mod, Option<String>)> {
    let old_mod = mods
        .iter()
        .find(|m| m.guid() == existing_guid)
        .cloned()
        .ok_or_else(|| anyhow::anyhow!("mod with GUID {{{}}} not found", existing_guid))
        .into_ta_result()?;
    let old_dir = old_mod.directory.clone();

    let staging_dir = state
        .base_path
        .join(MODS_DIRECTORY)
        .join(format!(".update-{}", Uuid::new_v4()));
    tokio::fs::create_dir_all(&staging_dir).await.into_ta_result()?;

    let staged = stage_update(&staging_dir, archive_path).await;

    let (mut manifest, warning) = match staged {
        Ok(ok) => ok,
        Err(e) => {
            let _ = tokio::fs::remove_dir_all(&staging_dir).await;
            return Err(e);
        }
    };

    let final_guid = if is_local_generated(&manifest) {
        if let Manifest::Legacy(legacy) = &mut manifest {
            legacy.guid = existing_guid;
        }
        existing_guid
    } else {
        let new_guid = match &manifest {
            Manifest::Legacy(m) => m.guid,
            Manifest::V1(m) => m.guid,
            Manifest::V2(m) => m.guid,
        };
        if new_guid != existing_guid {
            log::info!(
                "Update for mod {{{}}} ships its own GUID {{{}}}; keeping the new one (profile entries referencing the old GUID will no longer match).",
                existing_guid, new_guid
            );
        }
        new_guid
    };

    // Persist the (possibly GUID-rewritten) manifest into staging before the swap.
    let manifest_data = match serde_json::to_vec_pretty(&manifest) {
        Ok(d) => d,
        Err(e) => {
            let _ = tokio::fs::remove_dir_all(&staging_dir).await;
            return Err(e).into_ta_result();
        }
    };
    if let Err(e) = tokio::fs::write(staging_dir.join(MANIFEST_FILE), manifest_data).await {
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    log::info!("Swapping in updated content for mod {{{}}}...", final_guid);
    let backup_dir = state
        .base_path
        .join(MODS_DIRECTORY)
        .join(format!(".update-backup-{}", Uuid::new_v4()));

    if let Err(e) = tokio::fs::rename(&old_dir, &backup_dir).await {
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    if let Err(e) = tokio::fs::rename(&staging_dir, &old_dir).await {
        // Roll back: put the old content back where it was.
        let _ = tokio::fs::rename(&backup_dir, &old_dir).await;
        let _ = tokio::fs::remove_dir_all(&staging_dir).await;
        return Err(e).into_ta_result();
    }

    let _ = tokio::fs::remove_dir_all(&backup_dir).await;

    let mut new_mod = Mod {
        manifest,
        directory: old_dir,
        sources: Vec::new(),
    };

    if let Err(e) = new_mod.normalize_paths().await {
        log::error!("Path normalization failed: {}", e);
    }
    new_mod.resolve_sources().await;

    mods.retain(|m| m.guid() != existing_guid);
    mods.push(new_mod.clone());

    log::info!("Mod {{{}}} updated successfully.", new_mod.guid());
    Ok((new_mod, warning))
}

/// Extract `archive_path` into `staging_dir` and resolve its manifest
/// (generating a local one, with patch-layout auto-detection, if it ships
/// none), without touching anything outside `staging_dir`.
async fn stage_update(staging_dir: &Path, archive_path: &Path) -> TAResult<(Manifest, Option<String>)> {
    let archive = Archive::open(archive_path)?;
    let manifest_file = staging_dir.join(MANIFEST_FILE);
    let name = archive_path
        .file_prefix()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| "update".to_string());

    let (archive, mut manifest) = resolve_manifest(archive, name, manifest_file).await?;

    extract_archive(archive, staging_dir.to_path_buf()).await?;

    let warning = apply_patch_layout(staging_dir, &mut manifest).await.into_ta_result()?;

    Ok((manifest, warning))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::manifest::legacy;
    use std::io::Write;

    fn make_zip(path: &Path, entries: &[(&str, &[u8])]) {
        let file = std::fs::File::create(path).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        let options = zip::write::SimpleFileOptions::default();
        for (name, data) in entries {
            writer.start_file(*name, options).unwrap();
            writer.write_all(data).unwrap();
        }
        writer.finish().unwrap();
    }

    fn patch_file_name() -> String {
        "0123456789abcdef.patch_0".to_string()
    }

    async fn make_existing_mod(base: &Path, name: &str) -> (Uuid, PathBuf) {
        let mod_dir = base.join(MODS_DIRECTORY).join(name);
        tokio::fs::create_dir_all(&mod_dir).await.unwrap();
        tokio::fs::write(mod_dir.join(patch_file_name()), b"old content")
            .await
            .unwrap();

        let mut guid_bytes = [0u8; 16];
        guid_bytes[..5].copy_from_slice(b"LOCAL");
        guid_bytes[5] = 1;
        let guid = Uuid::from_bytes(guid_bytes);

        let manifest = Manifest::Legacy(legacy::Manifest {
            guid,
            name: name.to_string(),
            description: String::new(),
            icon_path: None,
            options: None,
        });
        let data = serde_json::to_vec_pretty(&manifest).unwrap();
        tokio::fs::write(mod_dir.join(MANIFEST_FILE), data)
            .await
            .unwrap();

        (guid, mod_dir)
    }

    #[tokio::test]
    async fn ensure_mods_loaded_marks_first_run_as_loaded() {
        let base = tempfile::tempdir().unwrap();
        let mut state_mods = None;
        let mods = ensure_mods_loaded(&mut state_mods, base.path()).await.unwrap();
        assert!(mods.is_empty());
        assert!(base.path().join(MODS_DIRECTORY).is_dir());
        // Previously the empty first-run list was returned but never stored,
        // so installs failed with "mods not read" until get_mods ran again.
        assert!(state_mods.is_some());
    }

    #[tokio::test]
    async fn ensure_mods_loaded_reads_existing_mods_once() {
        let base = tempfile::tempdir().unwrap();
        let (guid, _) = make_existing_mod(base.path(), "CoolMod").await;
        let mut state_mods = None;
        let mods = ensure_mods_loaded(&mut state_mods, base.path()).await.unwrap();
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), guid);
    }

    #[tokio::test]
    async fn install_update_keeps_old_guid_when_new_manifest_is_local_generated() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: old_dir.clone(),
            sources: Vec::new(),
        }];

        let update_zip = base.path().join("update.zip");
        make_zip(&update_zip, &[(&patch_file_name(), b"new content")]);

        let state = AppState::new(base.path().to_path_buf());
        let (updated, warning) = install_update_from_archive(&state, &mut mods, &update_zip, old_guid)
            .await
            .unwrap();

        assert!(warning.is_none());
        assert_eq!(updated.guid(), old_guid);
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), old_guid);

        let content = tokio::fs::read(old_dir.join(patch_file_name())).await.unwrap();
        assert_eq!(content, b"new content");
    }

    #[tokio::test]
    async fn install_update_keeps_new_guid_when_manifest_declares_its_own() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, _old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: base.path().join(MODS_DIRECTORY).join("CoolMod"),
            sources: Vec::new(),
        }];

        let new_manifest = serde_json::json!({
            "Guid": "11111111-1111-1111-1111-111111111111",
            "Name": "CoolMod",
            "Description": "shipped manifest",
        });
        let update_zip = base.path().join("update.zip");
        make_zip(
            &update_zip,
            &[
                (MANIFEST_FILE, serde_json::to_vec_pretty(&new_manifest).unwrap().as_slice()),
                (&patch_file_name(), b"new content"),
            ],
        );

        let state = AppState::new(base.path().to_path_buf());
        let (updated, _warning) = install_update_from_archive(&state, &mut mods, &update_zip, old_guid)
            .await
            .unwrap();

        let new_guid = Uuid::parse_str("11111111-1111-1111-1111-111111111111").unwrap();
        assert_eq!(updated.guid(), new_guid);
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), new_guid);
    }

    #[tokio::test]
    async fn install_update_leaves_old_mod_untouched_on_failure() {
        let base = tempfile::tempdir().unwrap();
        tokio::fs::create_dir_all(base.path().join(MODS_DIRECTORY))
            .await
            .unwrap();

        let (old_guid, old_dir) = make_existing_mod(base.path(), "CoolMod").await;
        let mut mods = vec![Mod {
            manifest: Manifest::Legacy(legacy::Manifest {
                guid: old_guid,
                name: "CoolMod".to_string(),
                description: String::new(),
                icon_path: None,
                options: None,
            }),
            directory: old_dir.clone(),
            sources: Vec::new(),
        }];

        // Not a real archive: Archive::open will fail on the unsupported/invalid content.
        let bad_path = base.path().join("update.exe");
        tokio::fs::write(&bad_path, b"not an archive").await.unwrap();

        let state = AppState::new(base.path().to_path_buf());
        let result = install_update_from_archive(&state, &mut mods, &bad_path, old_guid).await;

        assert!(result.is_err());
        assert_eq!(mods.len(), 1);
        assert_eq!(mods[0].guid(), old_guid);
        assert!(old_dir.join(patch_file_name()).is_file());
        let content = tokio::fs::read(old_dir.join(patch_file_name())).await.unwrap();
        assert_eq!(content, b"old content");
    }
}
